# FROM eclipse-temurin:17-jdk
# WORKDIR /app
# COPY target/da1agile-1.0-SNAPSHOT.jar app.jar
# CMD ["java", "-jar", "app.jar"]

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY target/*.jar app.jar
CMD ["java", "-jar", "app.jar"]